"""Add like_count and dislike_count to Post model

Revision ID: 3c72efaad4f1
Revises: 
Create Date: 2025-01-29 18:55:49.150265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72efaad4f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
